import { PlayerProfile } from '@/types'

// ─── Dummy player profile (shown when devRole === 'player') ───────────────────
export const DEMO_PLAYER_PROFILE = {
  id: 'demo-player-001',
  user_id: 'demo-user-player',
  first_name: 'Marcus',
  last_name: 'Williams',
  age: 22,
  nationality: 'English',
  gender: 'male' as const,
  height_cm: 180,
  weight_kg: 76,
  preferred_foot: 'right' as const,
  primary_position: 'CM',
  secondary_positions: ['CAM', 'CDM'],
  current_club: 'Hartfield United FC',
  contract_status: 'available_now' as const,
  league_level: 'Step 5',
  skill_level: 'High',
  profile_completion_score: 78,
  bio: 'Hardworking central midfielder with excellent vision and a knack for finding space in tight areas. Comfortable on the ball under pressure with good range of passing.',
  is_verified: true,
  is_featured: false,
  appearances: 34,
  goals: 6,
  assists: 11,
  clean_sheets: 0,
  profile_photo_url: null,
  highlight_reel_url: null,
}

// ─── Dummy scout profiles ─────────────────────────────────────────────────────
export const DEMO_SCOUT_FREE_PROFILE = {
  id: 'demo-scout-free-001',
  user_id: 'demo-user-scout-free',
  first_name: 'David',
  last_name: 'Chen',
  scout_type: 'freelance_scout' as const,
  organisation_name: 'Independent Scout',
  regions_covered: ['London', 'South East'],
  specialisms: ['Youth Development', 'Midfielders'],
  years_experience: 4,
  league_level: 'Step 3',
  is_verified: false,
  clearance_check: true,
  subscription_tier: 'free',
  created_at: '2024-09-01T00:00:00Z',
  updated_at: '2025-01-15T00:00:00Z',
}

export const DEMO_SCOUT_PRO_PROFILE = {
  id: 'demo-scout-pro-001',
  user_id: 'demo-user-scout-pro',
  first_name: 'Sarah',
  last_name: 'Mitchell',
  scout_type: 'club_scout' as const,
  affiliated_club: 'Northgate FC',
  organisation_name: 'Premier Sports Agency',
  regions_covered: ['North West', 'Yorkshire', 'Midlands'],
  specialisms: ['Strikers', 'Wingers', 'Data Analysis'],
  years_experience: 9,
  league_level: 'Championship',
  is_verified: true,
  clearance_check: true,
  subscription_tier: 'pro',
  created_at: '2023-03-12T00:00:00Z',
  updated_at: '2025-04-20T00:00:00Z',
}

// ─── Dummy players shown in the scout feed ────────────────────────────────────
export const DEMO_FEED_PLAYERS: PlayerProfile[] = [
  {
    id: 'demo-feed-001',
    user_id: 'demo-feed-user-001',
    first_name: 'Jordan',
    last_name: 'Okafor',
    age: 19,
    nationality: 'Nigerian',
    gender: 'male',
    height_cm: 175,
    weight_kg: 70,
    preferred_foot: 'left',
    primary_position: 'RW',
    secondary_positions: ['LW', 'CAM'],
    current_club: 'Riverside Athletic',
    contract_status: 'available_now',
    league_level: 'Step 4',
    skill_level: 'High',
    is_verified: false,
    is_featured: true,
    profile_photo_url: null,
    highlight_reel_url: null,
    profile_completion_score: 65,
    appearances: 22,
    goals: 9,
    assists: 7,
  },
  {
    id: 'demo-feed-002',
    user_id: 'demo-feed-user-002',
    first_name: 'Tom',
    last_name: 'Bradley',
    age: 24,
    nationality: 'English',
    gender: 'male',
    height_cm: 188,
    weight_kg: 84,
    preferred_foot: 'right',
    primary_position: 'CB',
    secondary_positions: ['RB'],
    current_club: 'Millfield Town',
    contract_status: 'available_eot',
    league_level: 'Step 5',
    skill_level: 'Medium',
    is_verified: true,
    is_featured: false,
    profile_photo_url: null,
    highlight_reel_url: null,
    profile_completion_score: 82,
    appearances: 41,
    goals: 3,
    assists: 2,
  },
  {
    id: 'demo-feed-003',
    user_id: 'demo-feed-user-003',
    first_name: 'Amara',
    last_name: 'Diallo',
    age: 21,
    nationality: 'French',
    gender: 'male',
    height_cm: 182,
    weight_kg: 78,
    preferred_foot: 'right',
    primary_position: 'ST',
    secondary_positions: ['CF'],
    current_club: 'Eastbrook FC',
    contract_status: 'available_now',
    league_level: 'Step 6',
    skill_level: 'High',
    is_verified: false,
    is_featured: false,
    profile_photo_url: null,
    highlight_reel_url: null,
    profile_completion_score: 71,
    appearances: 17,
    goals: 14,
    assists: 3,
  },
]
